littlebyteorg/appledb

bypassTweaks/a-bypass.json
bypassTweaks/choicy.json
bypassTweaks/flyjb-x.json
bypassTweaks/flyjb.json
bypassTweaks/hestia.json
bypassTweaks/hidejb.json
bypassTweaks/ihide.json
bypassTweaks/kernbypass.json
bypassTweaks/liberty-lite-(beta).json
bypassTweaks/libhooker-configurator.json
bypassTweaks/shadow.json
bypassTweaks/vnodebypass.json

We migrated to our Hugo website which uses a different URL hierarchy structure. This PR changes links to match the new location.
Also, I suggest putting the canonical URL of the repo in `repository.url`, and the sharerepo link in `repository.shareurl`. This will probably be a breaking change, but will be more useful if someone wants the canonical links.

Change links for documentation on bypass.beerpsi.me

---

jailbreakFiles/legacy/p0laris.js

ight, so I know that I technically don't have hard proof p0laris doesn't work on A6 and works on 9.3-9.3.4 as well, but I've observed it for some time now and the hardcoded offsets I see seem to be for 9.3.X - I've took a look through iOS 9.3.X's kernelcache and confirmed that the hardcoded offsets I could find it uses, such as the hardcoded allproc offset, proc_ucred offset, and _kernel_pmap, are definitely the same on 9.3-9.3.6 and NOT the correct offsets for previous firmwares. I actually mentioned this to spv, and he seemed to confirm this with me. Also, the _kernel_pmap is hardcoded to 0x003F6454, which would only be affective for 9.3.X A5/A5X, as for A6/A6X it's 0x003FE454, hence the pmap patch wouldn't work. It seems like for the rest I could find, offsets aren't hardcoded and …

fix p0laris support

---

iosFiles/macOS/21x - 12.x/21A559.json
iosFiles/macOS/21x - 12.x/21C52.json
iosFiles/macOS/21x - 12.x/21D49.json
iosFiles/macOS/21x - 12.x/21D62.json
iosFiles/macOS/21x - 12.x/21E230.json
iosFiles/macOS/21x - 12.x/21E258.json
iosFiles/macOS/21x - 12.x/21F79.json

I did macOS12 first because I'm testing generation of the [Firmware/Mac/12.x](https://www.theiphonewiki.com/wiki/Firmware/Mac/12.x) wiki page from appledb data (I thought that would be an easy one to start with). I will add links for other OSs later, if there's agreement with the JSON format.

Add release notes and security notes links for macOS 12.x

---

iosFiles/macOS/21x - 12.x/21F79.json

macOS 12.4 (21F79) was missing hashes. Added SHA-1, taken from Apple's `macOSIPSW.xml`.

Add SHA-1 hash for macOS 12.4

---

jailbreakFiles/legacy/winstaller.js

Adds missing iPhoneOS compatibility data from the Google Code repository.

Update winstaller.js to compatiblity

---

jailbreakFiles/legacy/openpwnage.js
jailbreakFiles/legacy/pangu9.js
jailbreakFiles/legacy/ppjailbreak.js
jailbreakFiles/legacy/taig.js

Prioritized PPJailbreak over TaiG. While PPJailbreak doesn't work on OTA Updated devices, that's still more functional than TaiG. I also added a note towards TaiG. Since openpwnage now has fully working Substrate, it's prioritized over PPJailbreak if 8.4. This shouldn't prioritize openpwnage over anything else except PPJailbreak.

openpwnage Build 8 + other

---

iosFiles/macOS/22x - 13.x/22A5295h.json

Add the ipsw source for macOS 13.0 beta 3, including file size and hashes. Also fix its release date (was July 5 and should be July 6).
(You should merge this by rebasing instead of  causing a useless merge commit :P)

macOS 13.0 beta 3: fix date and add ipsw

---

iosFiles/macOS/21x - 12.x/21G5056b.json
iosFiles/macOS/21x - 12.x/21G5063a.json
iosFiles/macOS/21x - 12.x/21G72-RC.json
iosFiles/macOS/21x - 12.x/21G72.json

- Fix release date of macOS 12.5 beta 4
- Fix ipsw of macOS 12.5 beta 5 (it was copy-pasted from beta 4)
- Add ipsw, release notes and security notes for macOS 12.5 RC and final
(I keep seeing useless merge commits, please rebase when accepting these changes >.>)

Multiple fixes to macOS 12 data

---

iosFiles/audioOS/19x - 15.x/19L5562e.json
iosFiles/tvOS/19x - 15.x/19J5268r.json
iosFiles/tvOS/19x - 15.x/19K5025g.json

Multiple fixes to audioOS and tvOS data, found while trying to generate theiphonewiki pages from appledb.

Misc tvOS/audioOS fixes

---

iosFiles/macOS/21x - 12.x/21A5248p.json
iosFiles/macOS/21x - 12.x/21A5268h.json
iosFiles/macOS/21x - 12.x/21A5284e.json
iosFiles/macOS/21x - 12.x/21A5294g.json
iosFiles/macOS/21x - 12.x/21A5304g.json
iosFiles/macOS/21x - 12.x/21A5506j.json
iosFiles/macOS/21x - 12.x/21A5522h.json
iosFiles/macOS/21x - 12.x/21A5534d.json
iosFiles/macOS/21x - 12.x/21A5543b.json
iosFiles/macOS/21x - 12.x/21A5552a.json
iosFiles/macOS/21x - 12.x/21A558.json
iosFiles/macOS/21x - 12.x/21A559-RC.json
iosFiles/macOS/21x - 12.x/21C5021h.json
iosFiles/macOS/21x - 12.x/21C5031d.json
iosFiles/macOS/21x - 12.x/21C5039b.json
iosFiles/macOS/21x - 12.x/21C5045a.json
iosFiles/macOS/21x - 12.x/21C51.json
iosFiles/macOS/21x - 12.x/21C52-RC.json
iosFiles/macOS/21x - 12.x/21D48.json
iosFiles/macOS/21x - 12.x/21D5025f.json
iosFiles/macOS/21x - 12.x/21D5039d.json
iosFiles/macOS/21x - 12.x/21E5196i.json
iosFiles/macOS/21x - 12.x/21E5206e.json
iosFiles/macOS/21x - 12.x/21E5212f.json
iosFiles/macOS/21x - 12.x/21E5222a.json
iosFiles/macOS/21x - 12.x/21E5227a.json
iosFiles/macOS/21x - 12.x/21F5048e.json

The data matches theiphonewiki now.
Please review the RCs in particular; I'm not sure if what I did with uniqueBuild is correct.

Add missing macOS 12.x betas

---

iosFiles/iOS/20x - 16.x/20A5328h.json
iosFiles/iPadOS/20x - 16.x/20A5328h.json
iosFiles/macOS/22x - 13.x/22A5311f.json
iosFiles/tvOS/20x - 16.x/20J5344f.json

This also adds iPad13,16 and iPad13,17 to the iPadOS deviceMap; please
check if I screwed something up.

Add ipsws for today's beta4

---

.gitignore
package-lock.json
package.json

This adds just the lightest bit of NPM allowing to pull the `apple-data` package, which can be used to generate or enrich any of the data files, also introduces using `grunt` as build framework to replace the deploy.js and python files with a repeatable step.

Added build infra and data dependency

---

iosFiles/iPadOS/19x - 15.x/19G69.json
iosFiles/iPadOS/19x - 15.x/19G71.json

They were added incorrectly in 93b00aaa, and only partially fixed in 3a3def38.

Fix iPadOS ipsw URLs

---

iosFiles/iOS/20x - 16.x/20A5349b.json
iosFiles/iPadOS/20x - 16.x/20A5349b.json
iosFiles/tvOS/20x - 16.x/20J5366a.json

Add firmware info and ipsw links for iOS and tvOS 16.0b6.
Still missing the firmwares without ipsws: watchOS, audioOS, and tvOS deviceMap should have AppleTV 4K.

Add iOS/tvOS 16.0 beta 6

---

iosFiles/iOS/19x - 15.x/19G82.json
iosFiles/iPadOS/19x - 15.x/19G82.json
iosFiles/macOS/21x - 12.x/21G83.json

Add JSON files for iOS 15.6.1 and macOS 12.5.1, including ipsws and release notes.

Add today's iOS 15.6.1 and macOS 12.5.1

---

iosFiles/audioOS/18x - 14.x/18K802.json
iosFiles/audioOS/18x - 14.x/18L569.json
iosFiles/audioOS/18x - 14.x/18M60.json
iosFiles/audioOS/19x - 15.x/19J346.json
iosFiles/audioOS/19x - 15.x/19J572.json
iosFiles/audioOS/19x - 15.x/19K52.json
iosFiles/audioOS/19x - 15.x/19L440.json
iosFiles/audioOS/19x - 15.x/19L570.json
iosFiles/iPadOS/19x - 15.x/19G71.json

`createDuplicateEntry` dicts for release candidates didn't have `"beta": true`; emiyl said they should have it

Add beta=true to "duplicate entry" release candidates

---

osFiles/iOS/19x - 15.x/19G82.json
osFiles/iPadOS/19x - 15.x/19G82.json
tasks/sort_os_files.py

These are files used by iTunes/Finder to show the update changelog when doing an ipsw update. They are listed on theiphonewiki.
The URL is different for iPod touch vs iPad vs iPhone, but as far as I know*, it's the same file for all iPhones on a given version. So I'm putting `"ipd": {"iPhone": "url", "iPad": "url", "iPod": "url"}` into each build json. Do you agree with this format?
(* if it turns out to be different for some iPhones/iPads, I'll find out when generating wiki pages from this, and we can figure out a different format)
What to do when there is only one device type, such as for iPadOS, or iOS 16? Should I use `"ipd": { "iPhone": "https://...iPhoneiOSShortRTF.ipd" }` or `"ipd": "https://...iPhoneiOSShortRTF.ipd"`? Personally I prefer the first because it makes things easier …

Add ipd links to iOS/iPadOS 15.6.1 as a first test

---

osFiles/iOS/19x - 15.x/19H349.json
osFiles/iOS/20x - 16.x/20F66.json
osFiles/iPadOS/19x - 15.x/19H349.json
osFiles/iPadOS/20x - 16.x/20F66.json
osFiles/macOS/20x - 11.x/20G1345.json
osFiles/macOS/21x - 12.x/21G646.json
osFiles/macOS/22x - 13.x/22F66.json
osFiles/watchOS/20x - 9.x/20T562.json

For all builds that had RC today, rename them to final build and move the RC stuff into createDuplicateEntries. Should save us some time on release day.
This is of course assuming there won't be an RC2 for anything, the macOS 11/12 final releases will match the last RC, etc. which is all subject to change. And this can't be merged until the dates are replaced from "2023-05-??" anyway...

Add final release of iOS 16.5 and others

---

osFiles/sdks/iOS/14B72.json

The data type is bool, not string.

Fix wrong data type for beta in iOS SDK 10.1 beta 4

---

jailbreakFiles/legacy/quickpwn.js

iPod Touch (2nd Generation) was added to quickpwn.js in https://github.com/littlebyteorg/appledb/commit/b8f2f24f2fde121b9104a1079eafd02e8807d252 (CC @emiyl)
However:
1. https://theapplewiki.com/wiki/Jailbreak/2.x claims that quickpwn doesn't support the iPod Touch 2
2. https://theapplewiki.com/wiki/QuickPwn has a screenshot demonstrating that the iPod Touch 2 isn't supported (obviously it could have been later updated though)
3. https://theapplewiki.com/wiki/Jailbreak_Exploits#QuickPwn_(2.0_-_2.2.1) claims that QuickPwn uses pwnage and pwnage 2.0, which both can't exploit the iPod Touch 2
4. https://mega.nz/folder/k4FAXCIB#Fk7pxs6ikYzL3YBvAGX5ig/folder/50lHETyB hosts quickpwn:
a. I don't have a MacBook, but the MacOS archives all contain …

Remove iPod Touch (2nd Generation) from quickpwn.js

---

.gitignore
.vscode/settings.json
schemas/osFiles.json

You can validate JSON files in `osFiles` against the schema to find several kinds of errors. The vscode workspace settings file also tells VS Code to use this schema, which provides inline validation as you type, and code completion.
I'm only enabling it for actual OSs for now. Other files like `osFiles/Software/Safari` needs a lot more stuff added to the schema first.

Add JSON Schema for osFiles, and configure it in VS Code

---

jailbreakFiles/rootlessjb4.js

Unlike the iPad 7th gen which didn't even support iOS 12, the iPod touch 7th gen is actually an A10 device that supports iOS 12 and should have been the one included in this list

Fix rootlessJB4 device list

---

jailbreakFiles/legacy/tetherbootx32.js

The official website considers the tool a semi-tether as of the March 2021 link (whereas it said tethered in the July 2020 archive), so we should upgrade its status to semi-tethered.

Upgrade TetherBootX32 to semi-tethered

---

jailbreakFiles/legacy/absinthe.json
jailbreakFiles/legacy/evasi0n.json
jailbreakFiles/legacy/g1lbertjb.json

- Can simplify jailbreaking for iOS 5.0-6.1.2, especially in the case of iOS 5

Update g1lbertJB priority

---

deviceFiles/Mac Studio/Mac13,2.json

Remove 24 and 32 core GPU and 16 core Neural Engine. Source: https://support.apple.com/en-us/111900

Correct GPU and NE core counts for Mac13,2

---

deviceFiles/Mouse/Magic Mouse (USB-C).json
deviceFiles/Trackpad/Magic Trackpad (USB-C).json

I came across a few issues with the new USB-C Magic Mouse/Trackpad files which were inconsistent with previous versions, so have fixed them in this PR:
* Change type of `Magic Mouse (USB-C)` from `Keyboard` to `Mouse`
* Change type of `Magic Trackpad (USB-C)` from `Keyboard` to `Trackpad`
* Also, move this file from `deviceFiles/Mouse` to `deviceFiles/Trackpad`

Fix type/location for USB-C Magic Mous/Trackpad

---

jailbreakFiles/legacy/unthredera1n.json

**Warning:** This is likely to cause previous links to this page to fail. If there is a proper protocol for this situation, do not merge this and implement this correction the proper way.
**Note:** This PR does not change the typo in the filename `/assets/images/jb-icons/unthreadera1n.png` because I'm unsure where it is

Correct typo unthreadera1n -> unthredera1n
